### ISSUE TITLE
[TEXTAREA] Composant View

### ISSUE THREAD

**Issue by tglatt** [tglatt/covidrome#12]
Faire un composant `TextAreaView` pour mettre la `value` sous le `label` et non à coté

<img width="593" alt="Capture d’écran 2020-04-10 à 11 48 02" src="https://user-images.githubusercontent.com/47273014/78981915-47fb2500-7b21-11ea-9dad-91c4d80ea128.png">

**Comment by nemolivier** [comment]
Il y a un retour chariot entre les deux lignes qui n'a pas été « vu ». Mais ce n'est pas du tout le plus urgent.

**Comment by tglatt** [comment]
<img width="1050" alt="Capture d’écran 2020-04-10 à 14 25 34" src="https://user-images.githubusercontent.com/47273014/78990747-87cd0700-7b37-11ea-8544-74032255577b.png">
