### ISSUE TITLE
La ddn disparaît quand on édite la fiche patient

### ISSUE THREAD

**Issue by nemolivier** [tglatt/covidrome#16]
Quand on édite les coordonnées de la fiche patient, la date de naissance n'apparaît pas (on voit dd/mm/yyyy).  Pourtant si on fait « enregistrer », la date précédemment entrée est bien toujours là.

**Comment by magopian** [comment]
Merci d'avoir remonté ce soucis, aussi remonté dans #14. C'est déjà réglé, mais pas encore en production.
Je met à jour le site d'ici peu ;)

**Comment by nemolivier** [comment]
Pardon, pas vu.

**Comment by magopian** [comment]
Aucun soucis ! J'ai mis à jour le site avec le correctif.
